---
- hosts: all
  user: root
  vars:
    hostip: ${ansible_eth0.ipv4.address}
    is_master: "'$hostip' == '$master_ip'"
    is_slave:  "not '$hostip' == '$master_ip'"
    dfs_replication: 2

  tasks:
  - name: install jdk 1.6
    action: apt name=openjdk-6-jdk state=latest install_recommends=no 

  - name: install sudo
    action: apt name=sudo state=latest install_recommends=no 

  - name: create hadoop group
    action: group name=hadoop state=present

  - name: create hadoop user
    action: user name=hduser group=hadoop ssh_key_file=/root/.ssh/id_rsa.pub

  - name: create hduser .ssh directory
    action: file path=~hduser/.ssh owner=hduser group=hadoop mode=0700 state=directory

  - name: copy authorized_keys to hduser .ssh directory
    tags: copyauth
    action: copy src=/root/.ssh/id_rsa.pub dest=~hduser/.ssh/authorized_keys owner=hduser group=hadoop mode=0600

  - name: prepare ssh 
    tags: preparessh
    action: |
      command /bin/sh -c '
      sudo -u hduser ssh-keygen -q -t rsa -P "" -f /home/hduser/.ssh/id_rsa
      sudo -u hduser cat /home/hduser/.ssh/id_rsa.pub >> /home/hduser/.ssh/authorized_keys'
    only_if: "$is_master"

  - name: copy master public ssh key to local box
    tags: copymasterssh
    local_action: command  scp -v -o StrictHostKeyChecking=no root@$master_ip:/home/hduser/.ssh/id_rsa.pub master_id_rsa_pub
    only_if: "$is_master"

  - name: copy local box master ssh key to hduser
    tags: slavessh
    authorized_key: user=hduser key="{{ lookup('file', 'master_id_rsa_pub') }}"
    only_if: "$is_slave"

  - name: disable IPV6
    tags: ipv6
    action: lineinfile dest=/etc/sysctl.conf state=present insertafter=EOF regexp="^"  line="net.ipv6.conf.all.disable_ipv6 = 1\nnet.ipv6.conf.default.disable_ipv6 = 1\nnet.ipv6.conf.lo.disable_ipv6 = 1"

  - name: update ~/.bashrc file
    tags: bashrc
    action: lineinfile dest=/home/hduser/.bashrc state=present insertafter=EOF regexp="^"  line="export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/\nexport HADOOP_HOME=/usr/local/hadoop\nexport HADOOP_OPTS=-Djava.net.preferIPv4Stack=true"

  - name: download hadoop src
    tags: downlo
    action: get_url dest=/usr/local url=http://apache.tsl.gr/hadoop/core/stable/hadoop-1.0.4.tar.gz

  - name: unzip hadoop src
    tags: unzip
    action: command tar -xzf hadoop-1.0.4.tar.gz chdir=/usr/local

  - name: chown hadoop-src from root to hadoop group
    tags: chown
    action: |
      command /bin/sh -c '
      cd /usr/local
      mv hadoop-1.0.4 hadoop
      chown -R hduser:hadoop hadoop'

  - name: update hadoop-env.sh file
    tags: env-sh
    action: lineinfile dest=/usr/local/hadoop/conf/hadoop-env.sh state=present insertafter=EOF regexp="^\# export JAVA_HOME=" line="export JAVA_HOME=/usr/lib/jvm/java-6-openjdk"

  - name: create app/hadoop/tmp to store HDFS
    tags: tmp
    action: |
      command /bin/sh -c '
      mkdir -p /app/hadoop/tmp
      chown hduser:hadoop /app/hadoop/tmp
      chmod 750 /app/hadoop/tmp'

  - include: conf-files.yml
  - include: format-hdfs.yml
