---
- hosts: all
  user: root
  vars:
     authorized_keys: "/root/.ssh/id_rsa.pub"
     master_ip: "83.212.114.84"

  tasks:
  - name: Set Ansible Key
    action: authorized_key user=root key="$HOME/.ssh/id_rsa.pub" state=present

  - name: install jdk 1.6
    action: apt name=openjdk-6-jdk state=latest install_recommends=no 

  - name: create hadoop group
    action: group name=hadoop state=present

  - name: create hadoop user
    action: user name=hduser group=hadoop ssh_key_file=/root/.ssh/id_rsa.pub

  - name: create hduser .ssh directory
    action: file path=~hduser/.ssh owner=hduser group=hadoop mode=0700 state=directory

  - name: copy authorized_keys to hduser .ssh directory
    tags: copyauth
    action: copy src=/root/.ssh/id_rsa.pub dest=~hduser/.ssh/authorized_keys owner=hduser group=hadoop mode=0600

  - name: disable IPV6
    tags: ipv6
    action: lineinfile dest=/etc/sysctl.conf state=present insertafter=EOF regexp="^"  line="net.ipv6.conf.all.disable_ipv6 = 1\nnet.ipv6.conf.default.disable_ipv6 = 1\nnet.ipv6.conf.lo.disable_ipv6 = 1"

  - name: update ~/.bashrc file
    tags: bashrc
    action: lineinfile dest=/home/hduser/.bashrc state=present insertafter=EOF regexp="^"  line="export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/\nexport HADOOP_HOME=/usr/local/hadoop\nexport HADOOP_OPTS=-Djava.net.preferIPv4Stack=true"

  - name: download hadoop src
    tags: downlo
    action: get_url dest=/usr/local url=http://apache.tsl.gr/hadoop/core/stable/hadoop-1.0.4.tar.gz

  - name: unzip hadoop src
    tags: unzip
    action: command tar -xzf hadoop-1.0.4.tar.gz chdir=/usr/local

  - name: chown hadoop-src from root to hadoop group
    tags: chown
    action: command mv hadoop-1.0.4 hadoop chdir=/usr/local
    action: command chown -R hduser:hadoop hadoop chdir=/usr/local

  - name: update hadoop-env.sh file
    tags: env-sh
    action: lineinfile dest=/usr/local/hadoop/conf/hadoop-env.sh state=present insertafter=EOF regexp="^\# export JAVA_HOME=" line="export JAVA_HOME=/usr/lib/jvm/java-6-openjdk"

  - name: create app/hadoop/tmp to store HDFS
    tags: tmp
    action: |
      command /bin/sh -c '
      mkdir -p /app/hadoop/tmp
      chown hduser:hadoop /app/hadoop/tmp
      chmod 750 /app/hadoop/tmp'

  - name: copy core-site.xml to /usr/local/hadoop/conf directory
    tags: copyxml0
    action: copy src=/root/hadoop/conf/core-site-template.xml dest=/usr/local/hadoop/conf/core-site.xml owner=hduser group=hadoop

  - name: modify core-site.xml to replace master ip
    tags: modifyxml0
    action: lineinfile dest=/usr/local/hadoop/conf/core-site.xml state=present regexp="MASTER_IP" line="  <value>hdfs://{{ master_ip }}:54310</value>"

  - name: copy mapred-site.xml to /usr/local/hadoop/conf directory
    tags: copyxml1
    action: copy src=/root/hadoop/conf/mapred-site-template.xml dest=/usr/local/hadoop/conf/mapred-site.xml owner=hduser group=hadoop

  - name: modify mapred-site.xml to replace master ip
    tags: modifyxml1
    action: lineinfile dest=/usr/local/hadoop/conf/mapred-site.xml state=present regexp="MASTER_IP" line="  <value>{{ master_ip }}:54311</value>"

  - name: copy hdfs-site.xml (with terasort-specific values) to /usr/local/hadoop/conf directory
    tags: copyxml2
    action: copy src=/root/hadoop/conf/hdfs-site.xml dest=/usr/local/hadoop/conf/hdfs-site.xml owner=hduser group=hadoop

