---
- hosts: master
  user: hduser
  vars:
    downloadURL: http://www.eu.apache.org/dist/hive/stable/hive-0.10.0.tar.gz
    srcFile: hive-0.10.0.tar.gz
    installDir: /home/hduser/hive-0.10.0

  tasks:
  - name: download Apache Hive 
    action: get_url dest=/home/hduser url=$downloadURL

  - name: unzip Hive  src
    tags: unzip
    action: command tar -xzf $srcFile chdir=/home/hduser

  - name: update $PATH
    tags: bashrc
    action: lineinfile dest=/home/hduser/.bashrc state=present insertafter=EOF regexp="^fi$"  line="fi\nexport PATH=$PATH:/home/hduser/hive-0.10.0/bin"
