---
- hosts: master
  user: root
  vars:
    downloadURL: http://www.eu.apache.org/dist/hive
    hive_version: hive-0.11.0

  tasks:
  - name: download Apache Hive 
    tags: download
    action: get_url dest=/usr/local url={{ downloadURL }}/{{ hive_version }}/{{ hive_version }}.tar.gz

  - name: chown hive from root to hadoop group
    tags: chown
    action: |
      command /bin/sh -c '
      cd /usr/local
      tar -xzf {{ hive_version }}.tar.gz
      mv {{ hive_version }} hive
      chown -R hduser:hadoop hive'

  - name: copy hive-site.xml to /usr/local/hive/conf directory
    tags: hivesite
    action: template src=/root/hadoop/hive/hive-site.j2 dest=/usr/local/hive/conf/hive-site.xml owner=hduser group=hadoop

  - name: update $PATH
    tags: bashrc
    action: lineinfile dest=/home/hduser/.bashrc state=present insertafter=EOF regexp="^" line="export PATH=$PATH:/usr/local/hive/bin"
